import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type Schema = { [key: string]: Json };
interface ContractType {
  name: string;
  reference: string;
}

const contractsRoot = path.resolve(import.meta.dirname, "..");
const schemasRoot = path.join(contractsRoot, "schemas");
const generatedRoot = path.join(contractsRoot, "generated");
const checkMode = process.argv.includes("--check");

async function loadSchemas(): Promise<Record<string, Schema>> {
  const registry: Record<string, Schema> = {};
  const families = (await readdir(schemasRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  for (const family of families) {
    const schemaPath = path.join(schemasRoot, family, `${family}.schema.json`);
    const schema = JSON.parse(await readFile(schemaPath, "utf8")) as Schema;
    const identifier = schema.$id;
    if (typeof identifier !== "string") {
      throw new Error(`${schemaPath} has no string $id`);
    }
    registry[identifier] = schema;
  }

  return registry;
}

function stableJson(value: Json): string {
  if (Array.isArray(value)) {
    return `[${value.map(stableJson).join(",")}]`;
  }
  if (value && typeof value === "object") {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function pascalCase(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

function contractTypes(registry: Record<string, Schema>): ContractType[] {
  return Object.entries(registry)
    .sort(([left], [right]) => left.localeCompare(right))
    .flatMap(([identifier, schema]) => {
      const fileName = identifier.split("/").at(-1) ?? "contract";
      const family = pascalCase(fileName.replace(".schema.json", ""));
      const definitions =
        schema.$defs && typeof schema.$defs === "object" && !Array.isArray(schema.$defs)
          ? Object.keys(schema.$defs).sort()
          : [];
      return definitions.map((definition) => ({
        name: `${family}${pascalCase(definition)}`,
        reference: `${identifier}#/$defs/${definition}`,
      }));
    });
}

function typescriptOutput(registryJson: string, types: ContractType[]): string {
  const declarations = types
    .map(
      ({ name, reference }) => `
export type ${name} = JsonValue & { readonly __contract: ${JSON.stringify(reference)} };
export function decode${name}(value: JsonValue): ${name} {
  return decodeContract(${JSON.stringify(reference)}, value) as ${name};
}`,
    )
    .join("\n")
    .trim();
  return `// Generated by packages/contracts/tools/generate.ts. Do not edit.
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

type Schema = boolean | { [key: string]: JsonValue };

export const schemaRegistry = ${registryJson} as const;

function resolvePointer(document: JsonValue, pointer: string): JsonValue {
  if (!pointer || pointer === "#") return document;
  if (!pointer.startsWith("#/")) throw new Error(\`unsupported ref pointer: \${pointer}\`);
  return pointer
    .slice(2)
    .split("/")
    .map((part) => part.replaceAll("~1", "/").replaceAll("~0", "~"))
    .reduce<JsonValue>((current, part) => {
      if (!current || typeof current !== "object" || Array.isArray(current)) {
        throw new Error(\`invalid ref pointer: \${pointer}\`);
      }
      const next = current[part];
      if (next === undefined) throw new Error(\`invalid ref pointer: \${pointer}\`);
      return next;
    }, document);
}

function resolveReference(
  reference: string,
  currentId: string,
): { schema: Schema; schemaId: string } {
  const [documentName, fragment = ""] = reference.split("#", 2);
  let schemaId = currentId;
  if (documentName) {
    const match = Object.keys(schemaRegistry).find(
      (candidate) =>
        candidate === documentName || candidate.endsWith(\`/\${documentName}\`),
    );
    if (!match) throw new Error(\`unknown schema reference: \${reference}\`);
    schemaId = match;
  }
  const document = (schemaRegistry as unknown as Record<string, Schema>)[schemaId];
  if (document === undefined) throw new Error(\`unknown schema: \${schemaId}\`);
  const resolved = resolvePointer(document, fragment ? \`#\${fragment}\` : "#");
  if (!resolved || typeof resolved !== "object" || Array.isArray(resolved)) {
    throw new Error(\`reference does not resolve to a schema: \${reference}\`);
  }
  return { schema: resolved as Schema, schemaId };
}

function isObject(value: unknown): value is Record<string, JsonValue> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function validateSchema(
  schema: Schema,
  value: JsonValue,
  schemaId: string,
  location: string,
  errors: string[],
): void {
  if (schema === false) {
    errors.push(\`\${location}: value is forbidden\`);
    return;
  }
  if (schema === true) return;
  if (typeof schema.$ref === "string") {
    const resolved = resolveReference(schema.$ref, schemaId);
    validateSchema(resolved.schema, value, resolved.schemaId, location, errors);
    return;
  }

  if (Array.isArray(schema.oneOf)) {
    const matches = schema.oneOf.filter((candidate) => {
      const candidateErrors: string[] = [];
      validateSchema(candidate as Schema, value, schemaId, location, candidateErrors);
      return candidateErrors.length === 0;
    }).length;
    if (matches !== 1) errors.push(\`\${location}: expected exactly one union variant\`);
  }

  if ("const" in schema && value !== schema.const) {
    errors.push(\`\${location}: expected constant \${JSON.stringify(schema.const)}\`);
  }
  if (Array.isArray(schema.enum) && !schema.enum.includes(value)) {
    errors.push(\`\${location}: value is not in the closed enum\`);
  }

  const expectedType = schema.type;
  if (expectedType === "object") {
    if (!isObject(value)) {
      errors.push(\`\${location}: expected object\`);
      return;
    }
    const properties = isObject(schema.properties) ? schema.properties : {};
    const required = Array.isArray(schema.required) ? schema.required : [];
    for (const field of required) {
      if (typeof field === "string" && !(field in value)) {
        errors.push(\`\${location}: missing required field \${field}\`);
      }
    }
    if (schema.additionalProperties === false) {
      for (const field of Object.keys(value)) {
        if (!(field in properties)) {
          errors.push(\`\${location}: unknown field \${field}\`);
        }
      }
    }
    for (const [field, child] of Object.entries(properties)) {
      if (field in value && (typeof child === "boolean" || isObject(child))) {
        validateSchema(child as Schema, value[field]!, schemaId, \`\${location}.\${field}\`, errors);
      }
    }
  } else if (expectedType === "array") {
    if (!Array.isArray(value)) {
      errors.push(\`\${location}: expected array\`);
      return;
    }
    if (typeof schema.maxItems === "number" && value.length > schema.maxItems) {
      errors.push(\`\${location}: too many items\`);
    }
    if (isObject(schema.items)) {
      value.forEach((item, index) =>
        validateSchema(schema.items as Schema, item, schemaId, \`\${location}[\${index}]\`, errors),
      );
    }
  } else if (expectedType === "string") {
    if (typeof value !== "string") {
      errors.push(\`\${location}: expected string\`);
      return;
    }
    const codePointLength = [...value].length;
    if (typeof schema.minLength === "number" && codePointLength < schema.minLength) {
      errors.push(\`\${location}: string is too short\`);
    }
    if (typeof schema.maxLength === "number" && codePointLength > schema.maxLength) {
      errors.push(\`\${location}: string is too long\`);
    }
    if (typeof schema.pattern === "string" && !new RegExp(schema.pattern).test(value)) {
      errors.push(\`\${location}: string does not match pattern\`);
    }
    if (
      schema.format === "date-time" &&
      (!/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?(?:Z|[+-]\\d{2}:\\d{2})$/.test(value) ||
        Number.isNaN(Date.parse(value)))
    ) {
      errors.push(\`\${location}: invalid date-time\`);
    }
  } else if (expectedType === "integer") {
    if (typeof value !== "number" || !Number.isSafeInteger(value)) {
      errors.push(\`\${location}: expected safe integer\`);
      return;
    }
  } else if (expectedType === "number" && typeof value !== "number") {
    errors.push(\`\${location}: expected number\`);
    return;
  } else if (expectedType === "boolean" && typeof value !== "boolean") {
    errors.push(\`\${location}: expected boolean\`);
    return;
  }

  if (typeof value === "number") {
    if (typeof schema.minimum === "number" && value < schema.minimum) {
      errors.push(\`\${location}: number is below minimum\`);
    }
    if (typeof schema.maximum === "number" && value > schema.maximum) {
      errors.push(\`\${location}: number is above maximum\`);
    }
  }
}

export function decodeContract(reference: string, value: JsonValue): JsonValue {
  const firstId = Object.keys(schemaRegistry).sort()[0];
  if (!firstId) throw new Error("schema registry is empty");
  const resolved = resolveReference(reference, firstId);
  const errors: string[] = [];
  validateSchema(resolved.schema, value, resolved.schemaId, "$", errors);
  if (errors.length > 0) throw new Error(errors.join("\\n"));
  return value;
}
${declarations}
`;
}

function pythonOutput(registryJson: string, types: ContractType[]): string {
  const declarations = types
    .map(
      ({ name, reference }) => `
class ${name}:
    def __init__(self, value: Any) -> None:
        self.value = decode_contract(${JSON.stringify(reference)}, value)
`,
    )
    .join("\n")
    .trim();
  return `# Generated by packages/contracts/tools/generate.ts. Do not edit.
from __future__ import annotations

import json
import math
import re
from datetime import datetime
from typing import Any

SCHEMA_REGISTRY: dict[str, dict[str, Any]] = json.loads(${JSON.stringify(registryJson)})


def _resolve_pointer(document: Any, pointer: str) -> Any:
    if not pointer or pointer == "#":
        return document
    if not pointer.startswith("#/"):
        raise ValueError(f"unsupported ref pointer: {pointer}")
    current = document
    for part in pointer[2:].split("/"):
        part = part.replace("~1", "/").replace("~0", "~")
        current = current[part]
    return current


def _resolve_reference(reference: str, current_id: str) -> tuple[dict[str, Any], str]:
    document_name, _, fragment = reference.partition("#")
    schema_id = current_id
    if document_name:
        matches = [
            candidate
            for candidate in SCHEMA_REGISTRY
            if candidate == document_name or candidate.endswith("/" + document_name)
        ]
        if len(matches) != 1:
            raise ValueError(f"unknown schema reference: {reference}")
        schema_id = matches[0]
    resolved = _resolve_pointer(
        SCHEMA_REGISTRY[schema_id], "#" + fragment if fragment else "#"
    )
    return resolved, schema_id


def _validate(schema: dict[str, Any] | bool, value: Any, schema_id: str, location: str) -> list[str]:
    if schema is False:
        return [f"{location}: value is forbidden"]
    if schema is True:
        return []
    if "$ref" in schema:
        resolved, resolved_id = _resolve_reference(schema["$ref"], schema_id)
        return _validate(resolved, value, resolved_id, location)
    if "oneOf" in schema:
        matches = sum(not _validate(candidate, value, schema_id, location) for candidate in schema["oneOf"])
        if matches != 1:
            errors = [f"{location}: expected exactly one union variant"]
        else:
            errors = []
    else:
        errors = []

    if "const" in schema and value != schema["const"]:
        errors.append(f"{location}: expected constant")
    if "enum" in schema and value not in schema["enum"]:
        errors.append(f"{location}: value is not in the closed enum")

    expected_type = schema.get("type")
    if expected_type == "object":
        if not isinstance(value, dict):
            return errors + [f"{location}: expected object"]
        properties = schema.get("properties", {})
        for field in schema.get("required", []):
            if field not in value:
                errors.append(f"{location}: missing required field {field}")
        if schema.get("additionalProperties") is False:
            for field in value:
                if field not in properties:
                    errors.append(f"{location}: unknown field {field}")
        for field, child in properties.items():
            if field in value:
                errors.extend(_validate(child, value[field], schema_id, f"{location}.{field}"))
    elif expected_type == "array":
        if not isinstance(value, list):
            return errors + [f"{location}: expected array"]
        if "maxItems" in schema and len(value) > schema["maxItems"]:
            errors.append(f"{location}: too many items")
        if "items" in schema:
            for index, item in enumerate(value):
                errors.extend(_validate(schema["items"], item, schema_id, f"{location}[{index}]"))
    elif expected_type == "string":
        if not isinstance(value, str):
            return errors + [f"{location}: expected string"]
        if len(value) < schema.get("minLength", 0):
            errors.append(f"{location}: string is too short")
        if len(value) > schema.get("maxLength", math.inf):
            errors.append(f"{location}: string is too long")
        if "pattern" in schema and re.search(schema["pattern"], value) is None:
            errors.append(f"{location}: string does not match pattern")
        if schema.get("format") == "date-time":
            try:
                if re.fullmatch(
                    r"\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?(?:Z|[+-]\\d{2}:\\d{2})",
                    value,
                ) is None:
                    raise ValueError
                datetime.fromisoformat(value.replace("Z", "+00:00"))
            except ValueError:
                errors.append(f"{location}: invalid date-time")
    elif expected_type == "integer":
        if isinstance(value, bool) or not isinstance(value, int):
            return errors + [f"{location}: expected integer"]
    elif expected_type == "number":
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            return errors + [f"{location}: expected number"]
    elif expected_type == "boolean" and not isinstance(value, bool):
        return errors + [f"{location}: expected boolean"]

    if isinstance(value, (int, float)) and not isinstance(value, bool):
        if value < schema.get("minimum", -math.inf):
            errors.append(f"{location}: number is below minimum")
        if value > schema.get("maximum", math.inf):
            errors.append(f"{location}: number is above maximum")
    return errors


def decode_contract(reference: str, value: Any) -> Any:
    first_id = sorted(SCHEMA_REGISTRY)[0]
    schema, schema_id = _resolve_reference(reference, first_id)
    errors = _validate(schema, value, schema_id, "$")
    if errors:
        raise ValueError("\\n".join(errors))
    return value

${declarations}
`;
}

function rustOutput(registryJson: string, types: ContractType[]): string {
  const declarations = types
    .map(
      ({ name, reference }) =>
        `define_contract_type!(${name}, ${JSON.stringify(reference)});`,
    )
    .join("\n")
    .trim();
  return `// Generated by packages/contracts/tools/generate.ts. Do not edit.
use chrono::DateTime;
use regex::Regex;
use serde_json::{Map, Value};

const SCHEMA_REGISTRY_JSON: &str = ${JSON.stringify(registryJson)};

fn registry() -> Map<String, Value> {
    serde_json::from_str(SCHEMA_REGISTRY_JSON).expect("generated schema registry")
}

fn resolve_pointer<'a>(document: &'a Value, pointer: &str) -> Result<&'a Value, String> {
    if pointer.is_empty() || pointer == "#" {
        return Ok(document);
    }
    let json_pointer = pointer
        .strip_prefix('#')
        .ok_or_else(|| format!("unsupported ref pointer: {pointer}"))?;
    document
        .pointer(json_pointer)
        .ok_or_else(|| format!("invalid ref pointer: {pointer}"))
}

fn resolve_reference<'a>(
    registry: &'a Map<String, Value>,
    reference: &str,
    current_id: &str,
) -> Result<(&'a Value, String), String> {
    let (document_name, fragment) = reference.split_once('#').unwrap_or((reference, ""));
    let schema_id = if document_name.is_empty() {
        current_id.to_owned()
    } else {
        registry
            .keys()
            .find(|candidate| *candidate == document_name || candidate.ends_with(&format!("/{document_name}")))
            .cloned()
            .ok_or_else(|| format!("unknown schema reference: {reference}"))?
    };
    let document = registry.get(&schema_id).ok_or_else(|| "missing schema".to_owned())?;
    let pointer = if fragment.is_empty() { "#".to_owned() } else { format!("#{fragment}") };
    Ok((resolve_pointer(document, &pointer)?, schema_id))
}

fn validate(
    registry: &Map<String, Value>,
    schema: &Value,
    value: &Value,
    schema_id: &str,
    location: &str,
) -> Vec<String> {
    if schema == &Value::Bool(false) {
        return vec![format!("{location}: value is forbidden")];
    }
    if schema == &Value::Bool(true) {
        return Vec::new();
    }
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return match resolve_reference(registry, reference, schema_id) {
            Ok((resolved, resolved_id)) => validate(registry, resolved, value, &resolved_id, location),
            Err(error) => vec![error],
        };
    }
    let mut errors = Vec::new();
    if let Some(one_of) = schema.get("oneOf").and_then(Value::as_array) {
        let matches = one_of
            .iter()
            .filter(|candidate| validate(registry, candidate, value, schema_id, location).is_empty())
            .count();
        if matches != 1 {
            errors.push(format!("{location}: expected exactly one union variant"));
        }
    }

    if let Some(constant) = schema.get("const") {
        if constant != value {
            errors.push(format!("{location}: expected constant"));
        }
    }
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        if !values.contains(value) {
            errors.push(format!("{location}: value is not in the closed enum"));
        }
    }

    match schema.get("type").and_then(Value::as_str) {
        Some("object") => {
            let Some(object) = value.as_object() else {
                errors.push(format!("{location}: expected object"));
                return errors;
            };
            let properties = schema.get("properties").and_then(Value::as_object);
            if let Some(required) = schema.get("required").and_then(Value::as_array) {
                for field in required.iter().filter_map(Value::as_str) {
                    if !object.contains_key(field) {
                        errors.push(format!("{location}: missing required field {field}"));
                    }
                }
            }
            if schema.get("additionalProperties") == Some(&Value::Bool(false)) {
                for field in object.keys() {
                    if !properties.is_some_and(|items| items.contains_key(field)) {
                        errors.push(format!("{location}: unknown field {field}"));
                    }
                }
            }
            if let Some(properties) = properties {
                for (field, child) in properties {
                    if let Some(child_value) = object.get(field) {
                        errors.extend(validate(
                            registry,
                            child,
                            child_value,
                            schema_id,
                            &format!("{location}.{field}"),
                        ));
                    }
                }
            }
        }
        Some("array") => {
            let Some(items) = value.as_array() else {
                errors.push(format!("{location}: expected array"));
                return errors;
            };
            if schema
                .get("maxItems")
                .and_then(Value::as_u64)
                .is_some_and(|maximum| items.len() as u64 > maximum)
            {
                errors.push(format!("{location}: too many items"));
            }
            if let Some(item_schema) = schema.get("items") {
                for (index, item) in items.iter().enumerate() {
                    errors.extend(validate(
                        registry,
                        item_schema,
                        item,
                        schema_id,
                        &format!("{location}[{index}]"),
                    ));
                }
            }
        }
        Some("string") => {
            let Some(text) = value.as_str() else {
                errors.push(format!("{location}: expected string"));
                return errors;
            };
            if schema
                .get("minLength")
                .and_then(Value::as_u64)
                .is_some_and(|minimum| text.chars().count() < minimum as usize)
            {
                errors.push(format!("{location}: string is too short"));
            }
            if schema
                .get("maxLength")
                .and_then(Value::as_u64)
                .is_some_and(|maximum| text.chars().count() > maximum as usize)
            {
                errors.push(format!("{location}: string is too long"));
            }
            if let Some(pattern) = schema.get("pattern").and_then(Value::as_str) {
                match Regex::new(pattern) {
                    Ok(expression) if !expression.is_match(text) => {
                        errors.push(format!("{location}: string does not match pattern"));
                    }
                    Err(error) => errors.push(format!("{location}: invalid schema pattern: {error}")),
                    _ => {}
                }
            }
            if schema.get("format").and_then(Value::as_str) == Some("date-time")
                && DateTime::parse_from_rfc3339(text).is_err()
            {
                errors.push(format!("{location}: invalid date-time"));
            }
        }
        Some("integer") => {
            if !value.is_i64() && !value.is_u64() {
                errors.push(format!("{location}: expected integer"));
                return errors;
            }
        }
        Some("number") => {
            if !value.is_number() {
                errors.push(format!("{location}: expected number"));
                return errors;
            }
        }
        Some("boolean") => {
            if !value.is_boolean() {
                errors.push(format!("{location}: expected boolean"));
                return errors;
            }
        }
        _ => {}
    }

    if let Some(number) = value.as_f64() {
        if schema
            .get("minimum")
            .and_then(Value::as_f64)
            .is_some_and(|minimum| number < minimum)
        {
            errors.push(format!("{location}: number is below minimum"));
        }
        if schema
            .get("maximum")
            .and_then(Value::as_f64)
            .is_some_and(|maximum| number > maximum)
        {
            errors.push(format!("{location}: number is above maximum"));
        }
    }
    errors
}

pub fn decode_contract(reference: &str, value: &Value) -> Result<(), Vec<String>> {
    let registry = registry();
    let first_id = registry.keys().min().expect("schema registry");
    let (schema, schema_id) =
        resolve_reference(&registry, reference, first_id).map_err(|error| vec![error])?;
    let errors = validate(&registry, schema, value, &schema_id, "$");
    if errors.is_empty() { Ok(()) } else { Err(errors) }
}

macro_rules! define_contract_type {
    ($name:ident, $reference:literal) => {
        #[derive(Clone, Debug, PartialEq)]
        pub struct $name(pub Value);

        impl TryFrom<Value> for $name {
            type Error = Vec<String>;

            fn try_from(value: Value) -> Result<Self, Self::Error> {
                decode_contract($reference, &value)?;
                Ok(Self(value))
            }
        }
    };
}

${declarations}
`;
}

async function writeGenerated(relativePath: string, content: string): Promise<boolean> {
  const outputPath = path.join(generatedRoot, relativePath);
  if (checkMode) {
    let existing = "";
    try {
      existing = await readFile(outputPath, "utf8");
    } catch {
      // Missing output is drift.
    }
    return existing !== content;
  }
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content);
  return false;
}

const registry = await loadSchemas();
const registryJson = stableJson(registry);
const types = contractTypes(registry);
const outputs: Array<[string, string]> = [
  ["typescript/contracts.ts", typescriptOutput(registryJson, types)],
  ["python/contracts.py", pythonOutput(registryJson, types)],
  ["rust/src/lib.rs", rustOutput(registryJson, types)],
];

let hasDrift = false;
for (const [relativePath, content] of outputs) {
  hasDrift = (await writeGenerated(relativePath, content)) || hasDrift;
}

if (checkMode && hasDrift) {
  console.error("generated contract drift");
  process.exitCode = 1;
}
